default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
      args: [--assume-in-merge]
    - id: detect-private-key
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.11
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.2.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
